default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: db
  
development:
  <<: *default
  database: twicro
  username: root
  password: password
  
test:
  <<: *default
  database: twicro
  username: root
  password: password

production:
  <<: *default
  database: db_production
  #username: user_production
  #password:
  #database: kyutechapp
  username: root
  password: yzjDIbkqnzi3nd0
  
